kind: pipeline
name: default

steps:
  - name: npm
    image: node:10.16
    group: vue
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install
      - yarn run build

  - name: scp
    image: appleboy/drone-scp
    group: vue
    settings:
      host:
        - drone-vue-stage.webfsd.com
      environment:
        STAGE_TARGET:
          from_secret: stage_target
      username: deployer
      key:
        from_secret: ssh_key
      port: 22
      command_timeout: 2m
      target: ${STAGE_TARGET}
      source: release.tar.gz

  - name: dingtalk-notify
    image: lddsb/drone-dingtalk-message
    settings:
      sha_link: true
      # message_pic: true
      message_color: true
      token:
        from_secret: dingtalk_robot_access_token
      type: markdown
    when:
      status:
        - failure
        - success

trigger:
  branch:
    - stage
    - master
