kind: pipeline
name: default

steps:
  - name: npm
    image: node:10.16
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install
      - yarn run build

  # http://plugins.drone.io/drillster/drone-rsync/
  - name: rsync
    image: drillster/drone-rsync
    environment:
      SSH_KEY:
        from_secret: ssh_key
      STAGE_TARGET:
        from_secret: stage_target
    hosts:
      - "drone-vue-stage.webfsd.com"
    key: ${SSH_KEY}
    source: ./dist
    target: ${STAGE_TARGET}
    include: ["**.*"]
    exclude: ["**.*"]
    script:
      - cd ${STAGE_TARGET} && ls -la

  - name: dingtalk-notify
    image: lddsb/drone-dingtalk-message
    settings:
      sha_link: true
      # message_pic: true
      message_color: true
      token:
        from_secret: dingtalk_robot_access_token
      type: markdown
    when:
      status:
        - failure
        - success

trigger:
  branch:
    - stage
    - master
