kind: pipeline
name: default

steps:
  - name: npm
    image: node:10.16
    commands:
      - node -v
      - npm -v
      - yarn --version
      - yarn config set cache-folder .yarn-cache
      - yarn install
      - yarn run build

  # http://plugins.drone.io/drillster/drone-rsync/
  - name: rsync
    image: drillster/drone-rsync
    environment:
      RSYNC_KEY:
        from_secret: rsync_key
      RSYNC_USER:
        from_secret: rsync_user
    settings:
      hosts:
        - drone-vue-stage.webfsd.com
      source: ./dist/*
      target: /var/www/codes/temp/drone-vue-stage.webfsd.com
      include:
        - "**.*"
      exclude:
        - "**.*"
      script:
        - cd /var/www/codes/temp/drone-vue-stage.webfsd.com && ls -la

  - name: dingtalk-notify
    image: lddsb/drone-dingtalk-message
    settings:
      sha_link: true
      # message_pic: true
      message_color: true
      token:
        from_secret: dingtalk_robot_access_token
      type: markdown
    when:
      status:
        - failure
        - success

trigger:
  branch:
    - stage
    - master
